#!/usr/bin/env bash
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"

# Ukončit předchozí proces(y) na portu 8080
PREV_PIDS=$(lsof -ti:8080 2>/dev/null || true)
if [ -n "$PREV_PIDS" ]; then
  echo "=== Ukončuji předchozí proces(y) na portu 8080 ==="
  echo "$PREV_PIDS" | xargs -r kill -9 2>/dev/null || true
  sleep 1
fi

echo "=== Instaluji závislosti frontendu ==="
(cd "$ROOT/frontend" && npm install --silent)

echo "=== Generuji git-commits.properties ==="
SHORT_HASH=$(git -C "$ROOT" rev-parse --short HEAD)
mkdir -p "$ROOT/backend/src/main/resources"
echo "# Auto-generated by start.sh" > "$ROOT/backend/src/main/resources/git-commits.properties"
echo "current=$SHORT_HASH" >> "$ROOT/backend/src/main/resources/git-commits.properties"
git -C "$ROOT" log --format="%H|||%s" -30 | while IFS='|||' read -r hash msg; do
  echo "$hash|||$msg" >> "$ROOT/backend/src/main/resources/git-commits.properties"
done
echo "git-commits.properties generated"

echo "=== Spouštím backend (Spring Boot, dev profil — H2) ==="
cd "$ROOT/backend"
echo "Active profiles: dev"
mvn spring-boot:run -s .mvn/settings.xml -q -Pdev -Dspring-boot.run.profiles=dev &
BACKEND_PID=$!
cd "$ROOT"

echo "=== Čekám na backend ==="
for i in $(seq 1 30); do
  if curl -sf http://localhost:8080/api/public/info > /dev/null 2>&1; then
    echo "Backend ready"
    break
  fi
  sleep 1
done

echo "=== Spouštím frontend (Vite) ==="
cd "$ROOT/frontend"
VITE_API_BASE_URL=http://localhost:8080 npm run dev &
FRONTEND_PID=$!
cd "$ROOT"

echo ""
echo "Backend:  http://localhost:8080 (dev profil, H2 databáze)"
echo "Frontend: http://localhost:5173 (API → localhost:8080)"
echo ""
echo "Zastavíš Ctrl+C"

trap "kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit" INT TERM
wait
