CREATE TABLE variant_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES edition(id),
    variant_code VARCHAR(50) NOT NULL,
    label VARCHAR(255) NOT NULL,
    registration_deadline DATE,
    race_date DATE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_variant_config_edition ON variant_config(edition_id);
ALTER TABLE variant_config ADD CONSTRAINT uq_variant_config_edition_variant UNIQUE (edition_id, variant_code);

INSERT INTO variant_config (edition_id, variant_code, label, registration_deadline, race_date, enabled)
SELECT id, 'JEDNODENNI', 'Jednodenní závod', '2026-06-06', '2026-06-07', TRUE FROM edition WHERE edition_year = 2026;

INSERT INTO variant_config (edition_id, variant_code, label, registration_deadline, race_date, enabled)
SELECT id, 'DVODENNI_UZAVRENO', 'Dvoudenní závod – UZAVŘENO', '2026-04-30', '2026-06-06', TRUE FROM edition WHERE edition_year = 2026;

INSERT INTO variant_config (edition_id, variant_code, label, registration_deadline, race_date, enabled)
SELECT id, 'DVODENNI_BEZ_UBYTOVANI', 'Dvoudenní závod bez ubytování', '2026-04-30', '2026-06-06', TRUE FROM edition WHERE edition_year = 2026;
