ALTER TABLE crew_member ADD COLUMN IF NOT EXISTS driver_age INT;
ALTER TABLE crew_member ADD COLUMN IF NOT EXISTS gender VARCHAR(10);
ALTER TABLE crew_member ADD COLUMN IF NOT EXISTS address VARCHAR(300);
ALTER TABLE crew_member ADD COLUMN IF NOT EXISTS club_member BOOLEAN;
ALTER TABLE crew_member ADD COLUMN IF NOT EXISTS first_time BOOLEAN;
